server:
  port: 8080

  error:
    include-binding-errors: always
spring:
  application:
    name: auth-sys
  datasource:
    url:  jdbc:postgresql://db:5432/auth
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day